"""
dbal.py -- real decode logic ported from the actual compiled firmware
(dbal/V010_015/DBAL.OUT), not reimplemented from scratch. research/
dbal_reader.py documents the container/discovery; this module is a
faithful Python port of specific DBAL.OUT functions, built directly from
a Ghidra decompilation of that file (see tools/dbal_decompiled.c,
generated by tools/ghidra_scripts/DecompileAll.java -- not committed,
570MB+ of Ghidra install/output, see .gitignore).

IMPORTANT, read before trusting any function below at face value:
every per-field byte EXTRACTION this project has cracked (eeu.rd's
header fields, eeu.iof's offset/count/type) goes through an external,
schema-driven reader object whose own vtable targets are NOT part of
DBAL.OUT's own resolvable code -- confirmed directly: Ghidra's
decompiler reports "Unable to disassemble EXTERNAL block location" for
every one of these calls. So the raw byte-level unpacking in this
module (`_unpack_rd_header`, `_unpack_iof_record`) is still OUR OWN,
independently validated via eeu.mod's binary field descriptors + real-
data correlation (see the wiki eeu-rd-Road-Routing-Graph.md/eeu-iof-
Parallel-Road-Array.md pages) -- NOT literally transliterated DBAL.OUT
code, because that code isn't present in this file to transliterate.

What IS directly, faithfully ported below -- real DBAL.OUT logic,
confirmed fully resolvable (no external/black-box calls), each checked
instruction-by-instruction against tools/dbal_decompiled.c:
  - FeaCoordReceiverInternal: eeuz.fea's real point-chain decoder
    (get_coordinates(), ported from getCoordinates__24FeaCoordReceiver
    Internal...) and its real Douglas-Peucker-style line-simplification
    pass (thinout()/_thinout_recursive(), ported from thinout__.../
    thinoutRecursive__...). Fully self-contained -- its only external
    call (thinout()) is itself ported here, not stubbed.
  - eeu_rd.apply_record_transform() -- the real `rdtype & 0x7fff`
    masking and delta->max-corner conversion
    (`maxLong = minLong + deltaLong`) read_current_record_from_database
    performs on top of the externally-read fields.
  - eeu_iof.gate_minor_road_list_offset()/gate_minor_road_count() -- the
    real validity-gating decision logic (type must be exactly 0 for
    offset to be valid; type==1 means the on-disk count is provisional)
    from db_get_minor_road_list_offset/db_get_minor_road_count_r_V005.

Two fields of FeaCoordReceiverInternal (`aux_buf`/`aux_int`, real struct
offsets +0x10/+0x14) are ported faithfully -- same arithmetic, same
control-flow role -- but their real-world MEANING was not determined;
they're plumbed through as opaque values, documented inline.
"""

import struct


# ============================================================================
# eeu.rd -- roadInfo bit layout. NOT a DBAL.OUT port (that byte's own
# extraction happens in the external reader, see module docstring) --
# this project's own crack via eeu.mod's binary field descriptors +
# real-data validation (wiki eeu-rd-Road-Routing-Graph.md), centralized
# here as the one place every caller decodes it from, instead of each
# caller re-deriving the same bit positions independently.
# ============================================================================

def decode_roadinfo_byte(roadinfo):
    """Decompose eeu.rd's roadInfo byte into its 6 real sub-fields --
    highway@bit0, preferred@bit1, explicate@bit2, ramp@bit3, name_type@
    bits4-6 (3-bit), interchange@bit7 -- exactly filling the byte with
    zero bits left over. Works on a plain int or a numpy array/column
    (every operator here is numpy-overloaded) -- callers needing just
    `highway` at numpy scale (e.g. road_naming.RdCache) can keep doing
    `roadinfo & 1` directly; this is for callers that want the full
    breakdown. Returns a dict of the 6 sub-values."""
    return {
        "highway": (roadinfo & 1) != 0,
        "preferred": ((roadinfo >> 1) & 1) != 0,
        "explicate": ((roadinfo >> 2) & 1) != 0,
        "ramp": ((roadinfo >> 3) & 1) != 0,
        "name_type": (roadinfo >> 4) & 0x7,
        "interchange": ((roadinfo >> 7) & 1) != 0,
    }


# ============================================================================
# eeu.rd -- the real transform read_current_record_from_database applies
# AFTER the (externally-read) fields, confirmed fully resolvable
# ============================================================================

def apply_rd_record_transform(rdtype_raw, min_long, min_lat, delta_long, delta_lat):
    """Faithful port of 3 real lines from read_current_record_from_
    database (tools/dbal_decompiled.c, search `rdtype_o`/`deltaLong_o`):

        *(ushort *)(param_2 + 0xe) = uVar6 & 0x7fff;          -- rdtype
        *(int *)(param_2 + 0x40) = iVar10 + *(int *)(param_2+0x38);  -- maxLong
        *(int *)(param_2 + 0x44) = iVar10 + *(int *)(param_2+0x3c);  -- maxLat

    `rdtype_raw`/`min_long`/`min_lat`/`delta_long`/`delta_lat` are this
    project's own already-validated raw field values (see module
    docstring -- the EXTRACTION itself isn't DBAL.OUT's own code, only
    this transform is). Returns (rdtype, max_long, max_lat)."""
    rdtype = rdtype_raw & 0x7fff
    max_long = min_long + delta_long
    max_lat = min_lat + delta_lat
    return rdtype, max_long, max_lat


# ============================================================================
# eeu.iof -- the real validity-gating logic, confirmed fully resolvable
# ============================================================================

def gate_minor_road_list_offset(type_raw, offset_raw):
    """Faithful port of db_get_minor_road_list_offset's real gate
    (tools/dbal_decompiled.c): returns `offset_raw` if `type_raw == 0`,
    else None (the real code returns -1/error and leaves the caller's
    output untouched for any other type value, 0x80 default included)."""
    if type_raw == 0:
        return offset_raw
    return None


def gate_minor_road_count(type_raw, count_raw, live_cache_status=None, live_cache_count=None):
    """Faithful port of db_get_minor_road_count_r_V005's real decision
    logic (tools/dbal_decompiled.c): `type_raw == 0` uses the on-disk
    count as-is; `type_raw == 1` means the on-disk count is PROVISIONAL
    -- the real firmware recomputes it from a live, runtime-built
    IntersectionList cache (db_minor_road_cache_get_status()/
    get_rec_count()) once that cache's own status reads `2` (ready).
    This project has no static copy of that runtime cache, so
    `live_cache_status`/`live_cache_count` default to None (unknown) --
    pass them only if you've independently reconstructed that cache.
    Returns `count_raw` unchanged whenever the live recompute isn't
    available, which is the real fallback behaviour for type==1 before
    the cache finishes loading."""
    if type_raw == 1 and live_cache_status == 2 and live_cache_count is not None:
        return live_cache_count
    return count_raw


# ============================================================================
# eeuz.fea -- FeaCoordReceiverInternal, fully self-contained real code
# ============================================================================

def _s16(v):
    v &= 0xffff
    return v - 0x10000 if v & 0x8000 else v


class FeaCoordReceiverInternal:
    """Faithful, instruction-by-instruction port of the real
    FeaCoordReceiverInternal class in DBAL.OUT (eeuz.fea's own relative
    point-chain decoder) -- init__24FeaCoordReceiverInternal... and
    getCoordinates__24FeaCoordReceiverInternal... in tools/
    dbal_decompiled.c. The real code decodes IN PLACE (the output
    LocalPoint cursor, `this+4`, starts at the SAME aligned address as
    the input delta-chain cursor and overwrites each 4-byte (dx,dy)
    record with its decoded (x,y) as it's consumed) -- this port
    preserves that: `data` is mutated in place, and `points` ends up
    holding (x, y) tuples read back out of the same bytearray.

    Still open (eeuz.fea's own wiki page): no absolute anchor is ever
    supplied by this code -- `accum_x`/`accum_y` always start at (0, 0)
    -- so `points` are real, decoded RELATIVE coordinates, not
    absolute lon/lat."""

    def __init__(self, data, offset, count, aux_buf, aux_int, mode, layer_props,
                 tol_x=0.0, tol_y=0.0):
        """`data`: a mutable bytearray containing the raw delta-chain
        (at least `offset + count*4` bytes). `offset`: starting byte
        offset of the first (dx, dy) record. `count`: number of 4-byte
        records available. `aux_buf`/`aux_int`: real struct fields
        +0x10/+0x14 -- ported faithfully (same control-flow role: a
        NULL/zero check in the finish path) but their real-world
        meaning was not determined by this project; pass 0/None if you
        don't have real values. `mode`: the real `ThinoutAccuracy` enum
        (0-3; `0` skips thinning -- the only value this port's
        `thinout()` is independently validated against; 1-3 are ported
        faithfully from the real code but not separately data-
        validated). `layer_props`: an object with real `.scale_x`/
        `.scale_y` attributes (FeaLayerPropertiesInternal's own +0x50/
        +0x54 fields -- this project has NOT cracked their real on-disk
        source/units; pass an object with scale_x=scale_y=1.0 for raw
        accumulated-delta units)."""
        self.data = data
        self.write_cur = offset & ~3
        self.read_cur = offset
        self.end = offset + count * 4
        self.aux_buf = aux_buf
        self.aux_int = aux_int
        self.accum_x = 0
        self.accum_y = 0
        self.first_iter_done = False
        self.mode = mode
        self.tol_x = tol_x
        self.tol_y = tol_y
        self.layer_props = layer_props
        self.points = []  # (x, y) tuples read back from `data` after decoding

    def get_coordinates(self):
        """Faithful port of getCoordinates__24FeaCoordReceiverInternal...
        Returns a dict {"status", "aux", "point_count", "cross_over"} --
        the real function's meaningful output params (a couple of the
        real signature's output params were pure duplicates in the
        decompiled C and are folded into these). Appends/overwrites
        `self.points`/`self.data` as a side effect, matching the real
        in-place semantics."""
        status = 1
        while True:
            if self.read_cur == self.end:
                return self._finish(0)

            run_write_start = self.write_cur
            cur = self.read_cur
            while cur < self.end:
                dx = _s16(struct.unpack_from(">h", self.data, cur)[0])
                dy = _s16(struct.unpack_from(">h", self.data, cur + 2)[0])
                cur += 4
                if dx == 0 and dy == 0 and self.first_iter_done:
                    break
                self.accum_x = _s16(self.accum_x + dx)
                self.accum_y = _s16(self.accum_y + dy)
                self.first_iter_done = True
                x = _s16(int(self.accum_x * self.layer_props.scale_x))
                y = _s16(int(self.accum_y * self.layer_props.scale_y))
                struct.pack_into(">hh", self.data, self.write_cur, x, y)
                self.write_cur += 4
            self.read_cur = cur

            point_count = (self.write_cur - run_write_start) // 4
            if self.mode != 0:
                # Real code first applies an "excess"-style bias to each
                # point just produced (x/y each nudged toward zero by 1
                # if negative, then bits 0-1 of both halves forced to 1)
                # before handing the run to thinout() -- ported inline.
                p = run_write_start
                while p < self.write_cur:
                    x, y = struct.unpack_from(">hh", self.data, p)
                    x = _s16(x + (-1 if x < 0 else 0))
                    y = _s16(y + (-1 if y < 0 else 0))
                    word = struct.unpack_from(">I", self.data, p)[0]
                    struct.pack_into(">I", self.data, p, (word & 0xfffcfffc) | 0x30003)
                    struct.pack_into(">hh", self.data, p, x, y)
                    p += 4
                point_count = self.thinout(run_write_start, point_count)

            if (point_count > 0 and self.mode == 0) or (point_count > 1 and self.mode == 2):
                return self._finish(status, point_count)
            if point_count < 3:
                if self.mode == 3:
                    word = struct.unpack_from(">I", self.data, run_write_start)[0]
                    struct.pack_into(">I", self.data, run_write_start, word & 0xfffcfffc)
                    return self._finish(status, 1)
            elif self.mode in (1, 3):
                return self._finish(status, point_count)

            if self.read_cur == self.end:
                status = 0

    def _finish(self, status, point_count=0):
        if not self.aux_buf:
            result = {"status": -2, "aux": None, "point_count": 0, "cross_over": 0}
        else:
            aux = self.aux_buf if self.aux_int else None
            result = {
                "status": 0 if self.aux_int else -1,
                "aux": self.aux_int,
                "point_count": point_count,
                "cross_over": 0,
            }
            self.aux_buf = 0
        self.points = [
            struct.unpack_from(">hh", self.data, i)
            for i in range(self.write_cur - point_count * 4, self.write_cur, 4)
        ] if point_count else []
        return result

    def thinout(self, start, count):
        """Faithful port of thinout__24FeaCoordReceiverInternal... --
        a single-pass sweep that groups consecutive points within a
        layer-defined half-width/half-height box of their run's own
        start into one thinout_recursive() call per out-of-box break.
        Returns the new (possibly smaller) point count.

        HONESTY NOTE: the real code reads this bound from
        `layer_props`'s own +0x20/+0x24 fields (`layer_props.f20`/
        `.f24` below -- real struct offsets, kept as the attribute name
        since this project has NOT independently confirmed their exact
        real-world meaning/units, only that db_fea_init_V005 rebalances
        them via a divisor search at load time, see wiki eeuz-fea-
        Place-Name-Gazetteer.md). Pass a `layer_props` with these set
        to 0 (the default via getattr below) to disable this bound
        entirely -- every point then triggers its own
        thinout_recursive() call, which is always structurally safe,
        just not necessarily numerically faithful to the real disc's
        own tuning for these 2 fields specifically."""
        half_x = _s16(getattr(self.layer_props, "f20", 0) >> 1)
        half_y = _s16(getattr(self.layer_props, "f24", 0) >> 1)
        write_out = [start]
        run_start = start
        first = True
        p = start
        end = start + count * 4
        while p < end:
            x, y = struct.unpack_from(">hh", self.data, p)
            x = _s16(x + (-1 if x < 0 else 0))
            y = _s16(y + (-1 if y < 0 else 0))
            struct.pack_into(">hh", self.data, p, x, y)
            word = struct.unpack_from(">I", self.data, p)[0]
            struct.pack_into(">I", self.data, p, word & 0xfffcfffc)
            if (x < -half_x or half_x <= x or y < -half_y or half_y <= y
                    or first or p == end - 4):
                self._thinout_recursive(run_start, p, 0xf, write_out)
                run_start = p
            first = False
            p += 4
        return (write_out[0] - start) // 4

    def _thinout_recursive(self, lo, hi, level, write_out):
        """Faithful port of thinoutRecursive__24FeaCoordReceiverInternal...
        -- real Douglas-Peucker-style line simplification: find the
        point between `lo`/`hi` furthest from the lo-hi chord; if that
        distance clears a real threshold, recurse on both halves,
        otherwise collapse the whole span to its `hi` endpoint.

        HONESTY NOTE: the real code compares against a per-level
        distance read from a table at `layer_props+0x28` (an array
        indexed by `level`) against 2 more real global double constants
        this project tried and failed to extract a plausible value for
        (the addresses Ghidra's decompiler names don't map cleanly onto
        a file offset in this object -- likely a literal-pool/relocated
        constant this project's quick lookup attempt got wrong, not
        confirmed to genuinely be zero). This port exposes that
        comparison as `self.layer_props.level_dist` (a plain list
        indexed by level, real units/values NOT recovered) -- pass
        `None` (the default) to always recurse maximally, which is
        structurally safe but not numerically faithful to the real
        disc's own thinning aggressiveness. Ported for completeness;
        not independently re-validated against real output the way the
        simpler delta-accumulation loop above was."""
        if (hi - lo) // 4 > 1:
            x0, y0 = struct.unpack_from(">hh", self.data, lo)
            x1, y1 = struct.unpack_from(">hh", self.data, hi)
            dx = (x1 - x0) * self.tol_x
            dy = (y1 - y0) * self.tol_y
            best_p, best_d2 = None, 0.0
            p = lo + 4
            while p < hi:
                x, y = struct.unpack_from(">hh", self.data, p)
                t = (x - x0) * self.tol_x * dx + (y - y0) * self.tol_y * dy
                px, py = x0, y0
                if t > 0.0:
                    denom = dx * dx + dy * dy
                    if t < denom:
                        t /= denom
                        px = t * (x1 - x0) + x0
                        py = t * (y1 - y0) + y0
                    else:
                        px, py = x1, y1
                ex = (x - px) * self.tol_x
                ey = (y - py) * self.tol_y
                d2 = ex * ex + ey * ey
                if d2 > best_d2:
                    best_p, best_d2 = p, d2
            import math
            dist = math.sqrt(best_d2) if best_d2 else 0.0
            level_dist = getattr(self.layer_props, "level_dist", None)
            if level_dist is not None:
                lvl = level
                while lvl >= 0:
                    if level_dist[lvl] < dist * getattr(self.layer_props, "dist_scale", 1.0):
                        self._thinout_recursive(lo, best_p, lvl, write_out)
                        self._thinout_recursive(best_p, hi, lvl, write_out)
                        out = write_out[0] - 4
                        word = struct.unpack_from(">I", self.data, out)[0]
                        struct.pack_into(">I", self.data, out,
                                          (word & 0xfffcfffc) | (level & 3) | ((level & 0xc) << 14))
                        return
                    lvl -= 1
        word = struct.unpack_from(">I", self.data, hi)[0]
        dest = write_out[0]
        struct.pack_into(">I", self.data, dest,
                          (word & 0xfffcfffc) | (level & 3) | ((level & 0xc) << 14))
        write_out[0] = dest + 4
